// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-QAMcPE0kEIyuXr-mXrEhJ5fiL73k1_o',
    appId: '1:796669288308:web:c1bc1f7293f9007078d621',
    messagingSenderId: '796669288308',
    projectId: 'owaravi',
    authDomain: 'owaravi.firebaseapp.com',
    storageBucket: 'owaravi.appspot.com',
    measurementId: 'G-TXGHLCL5KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ4kvLKYTSJSs-bEsAP6Kfs3F3Rop3lm8',
    appId: '1:796669288308:android:007b6b725d6a99a578d621',
    messagingSenderId: '796669288308',
    projectId: 'owaravi',
    storageBucket: 'owaravi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPpuqu3s4aAJWx76GQKdshN7l3cgmSRYg',
    appId: '1:796669288308:ios:58909d8ec9b8e29178d621',
    messagingSenderId: '796669288308',
    projectId: 'owaravi',
    storageBucket: 'owaravi.appspot.com',
    iosBundleId: 'com.example.owaraviApp',
  );
}
